colleges = [{'College': 'Adelphi  University',
'State': 'NY',
'Coach': 'Jennifer Henick'},{'College': 'Adrian College',
'State': 'MI',
'Coach': 'Jaclynn Gray'},{'College': 'Albion College',
'State': 'MI',
'Coach': 'Randi Gardner'},{'College': 'Alfred State College',
'State': 'NY',
'Coach': 'Victoria Bolton'},{'College': 'Alfred University',
'State': 'NY',
'Coach': 'Nancy Kohler'},{'College': 'Allegheny College',
'State': 'PA',
'Coach': 'Halli Bidwell'},{'College': 'Alma College',
'State': 'MI',
'Coach': 'Emily Pittman'},{'College': 'American University',
'State': 'DC',
'Coach': 'Star Dalley'},{'College': 'Amherst College',
'State': 'MA',
'Coach': 'Beth Manning'},{'College': 'Appalachian State University',
'State': 'NC',
'Coach': 'Sarah Klassett'},{'College': 'Arcadia University',
'State': 'PA',
'Coach': 'Amber Jewell'},{'College': 'Arizona State University',
'State': 'AZ',
'Coach': 'Rachel Jansen'},{'College': 'Assumption College',
'State': 'MA',
'Coach': 'Joy Sigona'},{'College': 'Auburn University',
'State': 'AL',
'Coach': 'Lisa Dorsey'},{'College': 'Augustana College',
'State': 'IL',
'Coach': 'Julie Mann'},{'College': 'Ave Maria University',
'State': 'FL',
'Coach': "Katie O'Hare"},{'College': 'Averett University',
'State': 'VA',
'Coach': 'Cricket Stone'},{'College': 'Ball State University',
'State': 'IN',
'Coach': 'Tammie Jones'},{'College': 'Bard College',
'State': 'NY',
'Coach': 'Sharon Bach'},{'College': 'Bates College',
'State': 'ME',
'Coach': 'Stephanie Plaisted'},{'College': 'Becker College',
'State': 'MA',
'Coach': 'Nicole Eastman'},{'College': 'Belmont University',
'State': 'TN',
'Coach': 'Beth Bankemper'},{'College': 'Bennington College',
'State': 'VT',
'Coach': 'Tara Lowary'},{'College': 'Bentley University',
'State': 'MA',
'Coach': 'Melissa Consalvo'},{'College': 'Berry College',
'State': 'GA',
'Coach': 'Margaret Knight'},{'College': 'Bethany College',
'State': 'WV',
'Coach': 'Beth Johnson'},{'College': 'Binghamton University',
'State': 'NY',
'Coach': 'Mary Celeste "Mimi" Penfield'},{'College': 'Black Hawk College',
'State': 'IL',
'Coach': 'Donna Irvin'},{'College': 'Bloomsburg University',
'State': 'PA',
'Coach': 'Amie Wolfinger'},{'College': 'Boston College',
'State': 'MA',
'Coach': 'Sheila Dunham'},{'College': 'Boston University',
'State': 'MA',
'Coach': 'Phyllis Cervelli'},{'College': 'Bowdoin College',
'State': 'ME',
'Coach': 'Virginia Shaw'},{'College': 'Bowling Green State University',
'State': 'OH',
'Coach': 'Jill Jewett'},{'College': 'Brandeis University',
'State': 'MA',
'Coach': 'Katie Bobola'},{'College': 'Bridgewater College',
'State': 'VA',
'Coach': 'Jerry Schurink'},{'College': 'Bridgewater State University',
'State': 'MA',
'Coach': 'Geraldine Burnet'},{'College': 'Brock University',
'State': 'ON',
'Coach': 'Shara Pavan'},{'College': 'Brockport College',
'State': 'NY',
'Coach': 'Jolene Hasseler'},{'College': 'Brown University',
'State': 'RI',
'Coach': 'Michaela Scanlon'},{'College': 'Bucknell University',
'State': 'PA',
'Coach': 'Farra Phillips-Hillyard'},{'College': 'Bucks County Community College',
'State': 'PA',
'Coach': 'Patricia Silcox'},{'College': 'Butler University',
'State': 'IN',
'Coach': 'Dawn Stumm'},{'College': 'Cal Poly State University, San Luis Obispo',
'State': 'CA',
'Coach': 'Natalie Baker'},{'College': 'California State Polytechnic University Pomona',
'State': 'CA',
'Coach': 'Hailey Quirk'},{'College': 'California State University, Fullerton',
'State': 'CA',
'Coach': 'Mercedes Hanson'},{'College': 'California University of Pennsylvania',
'State': 'PA',
'Coach': 'Susan Malencia'},{'College': 'Calvin College',
'State': 'MI',
'Coach': 'Kris McAfee'},{'College': 'Campbell University',
'State': 'NC',
'Coach': 'Michelle Stephenson'},{'College': 'Canisius College',
'State': 'NY',
'Coach': 'Judy West'},{'College': 'Case Western Reserve University',
'State': 'OH',
'Coach': 'Allison Park'},{'College': 'Castleton University',
'State': 'VT',
'Coach': "Judy O'Rourke"},{'College': 'Cazenovia College',
'State': 'NY',
'Coach': 'Amy Sherrick-von Schiller'},{'College': 'Centenary College',
'State': 'NJ',
'Coach': 'Heather Clark'},{'College': 'Central Connecticut State University',
'State': 'CT',
'Coach': 'Kayla Blanchette'},{'College': 'Central Michigan University',
'State': 'MI',
'Coach': 'Melanie Blues'},{'College': 'Central Washington University',
'State': 'WA',
'Coach': 'Tessa Churchill'},{'College': 'Chapman University',
'State': 'CA',
'Coach': 'Jessica Bower'},{'College': 'Chestnut Hill College',
'State': 'PA',
'Coach': 'Amanda Enwright'},{'College': 'Christopher Newport University',
'State': 'VA',
'Coach': 'Ryann Winn'},{'College': 'Claremont Colleges',
'State': 'CA',
'Coach': 'Mercedes Hanson'},{'College': 'Clarion University Venango Campus',
'State': 'PA',
'Coach': 'Tammy Braham'},{'College': 'Clark University',
'State': 'MA',
'Coach': 'Sarah Grogan'},{'College': 'Clemson University',
'State': 'SC',
'Coach': 'Rebecca Shirley'},{'College': 'Coastal Carolina University',
'State': 'SC',
'Coach': 'Kristina Crumlish'},{'College': 'Colby Community College',
'State': 'KS',
'Coach': 'Shanda Mattix'},{'College': 'Colby Sawyer College',
'State': 'NH',
'Coach': 'Pamela Payson'},{'College': 'Colgate University',
'State': 'NY',
'Coach': 'Anna Hackney'},{'College': 'College of Central Florida',
'State': 'FL',
'Coach': 'Judy Downer'},{'College': 'College of Charleston',
'State': 'SC',
'Coach': 'Robert Story'},{'College': 'College of the Holy Cross',
'State': 'MA',
'Coach': 'Frank Perla'},{'College': 'College of the Sequoias',
'State': 'CA',
'Coach': 'Kim Pitigliano'},{'College': 'College Of William And Mary',
'State': 'VA',
'Coach': 'Karen Greenwood'},{'College': 'College Of Wooster',
'State': 'OH',
'Coach': 'Karla Forrer'},{'College': 'Colorado College',
'State': 'CO',
'Coach': 'Tracey Powers'},{'College': 'Colorado Northwestern Community College',
'State': 'CO',
'Coach': 'Miranda Morris'},{'College': 'Colorado School of Mines',
'State': 'CO',
'Coach': 'Jennifer Duffy'},{'College': 'Colorado State University',
'State': 'CO',
'Coach': 'Kathy Montgomery'},{'College': 'Columbia University',
'State': 'NY',
'Coach': 'Penny Kinnally'},{'College': 'Connecticut College',
'State': 'CT',
'Coach': 'Richard Luckhardt'},{'College': 'Converse College',
'State': 'SC',
'Coach': 'Lincoln Russell'},{'College': 'Cornell University',
'State': 'NY',
'Coach': 'Joanna Novakovic'},{'College': 'Curry College',
'State': 'MA',
'Coach': 'Jennifer Sullivan'},{'College': 'Dartmouth College',
'State': 'NH',
'Coach': 'Sally Batton'},{'College': 'Delaware Valley University',
'State': 'PA',
'Coach': 'Cory Kieschnick'},{'College': 'Denison University',
'State': 'OH',
'Coach': 'Claudia Hutchinson'},{'College': 'DeSales University',
'State': 'PA',
'Coach': 'Sue Casale'},{'College': 'Dickinson College',
'State': 'PA',
'Coach': 'Lindsay Vulich'},{'College': 'Drew University',
'State': 'NJ',
'Coach': 'Karen Sykes'},{'College': 'Drexel University',
'State': 'PA',
'Coach': 'Elizabeth Orem'},{'College': 'Duke University',
'State': 'NC',
'Coach': 'Virginia Rollins'},{'College': 'Duquesne University',
'State': 'PA',
'Coach': 'Linda Stevens'},{'College': 'Earlham College',
'State': 'IN',
'Coach': 'Kellie Riggott'},{'College': 'East Carolina University',
'State': 'NC',
'Coach': 'Caroline Jackson'},{'College': 'East Stroudsburg University',
'State': 'PA',
'Coach': 'Pat Speziale'},{'College': 'Eastern Illinois University',
'State': 'IL',
'Coach': 'Kandi Lane'},{'College': 'Edinboro University of Pennsylvania',
'State': 'PA',
'Coach': 'Lew Trumble'},{'College': 'Ellsworth Community College',
'State': 'IA',
'Coach': 'Lisa Jorgensen'},{'College': 'Elmira College',
'State': 'NY',
'Coach': 'MaryLou Spencer'},{'College': 'Elon University',
'State': 'NC',
'Coach': 'Anne Morgan'},{'College': 'Emory & Henry College',
'State': 'VA',
'Coach': 'Heather McCloud'},{'College': 'Emory University',
'State': 'GA',
'Coach': 'Robyn Sonis'},{'College': 'Endicott College',
'State': 'MA',
'Coach': 'Bethany Jones'},{'College': 'Fairfield University',
'State': 'CT',
'Coach': 'Naomi Gauruder'},{'College': 'Ferris State University',
'State': 'MI',
'Coach': 'Brianna Slager'},{'College': 'Ferrum College',
'State': 'VA',
'Coach': 'Margaret Cornwell'},{'College': 'Florida Atlantic University',
'State': 'FL',
'Coach': 'Tricia Carron'},{'College': 'Florida Gulf Coast University',
'State': 'FL',
'Coach': 'Roger Seitzmeir'},{'College': 'Florida International University',
'State': 'FL',
'Coach': 'Daniela Roy'},{'College': 'Florida Southern College',
'State': 'FL',
'Coach': 'Shannon Morrell'},{'College': 'Florida State University',
'State': 'FL',
'Coach': 'Jean Anthony'},{'College': 'Franciscan University',
'State': 'OH',
'Coach': 'Marissa Gump'},{'College': 'Franklin and Marshall College',
'State': 'PA',
'Coach': 'Gillian Beale King'},{'College': 'Furman University',
'State': 'SC',
'Coach': 'Leslie Huffman'},{'College': 'George Mason University',
'State': 'VA',
'Coach': 'Sue Buscher'},{'College': 'George Washington University',
'State': 'MD',
'Coach': 'Cindy Newberry'},{'College': 'Georgetown College',
'State': 'KY',
'Coach': 'Nori Scheffel'},{'College': 'Georgetown University',
'State': 'DC',
'Coach': 'Jeffrey Becker'},{'College': 'Georgia College and State University',
'State': 'GA',
'Coach': 'Carly Hunter'},{'College': 'Georgia Institute of Technology',
'State': 'GA',
'Coach': 'Emily Tomlinson'},{'College': 'Georgia Southern University',
'State': 'GA',
'Coach': 'Eleanor Ellis'},{'College': 'Georgia State University',
'State': 'GA',
'Coach': 'Karen Kerby'},{'College': 'Gettysburg College',
'State': 'PA',
'Coach': 'Janis Groomes'},{'College': 'Goucher College',
'State': 'MD',
'Coach': 'Jennifer Bunty'},{'College': 'Grand Valley State University',
'State': 'MI',
'Coach': 'Kris McAfee'},{'College': 'Grove City College',
'State': 'PA',
'Coach': 'Tammy Braham'},{'College': 'Gustavus Adolphus College',
'State': 'MN',
'Coach': 'Lauren Wood'},{'College': 'Gwynedd-Mercy College',
'State': 'PA',
'Coach': 'Amanda Enwright'},{'College': 'Hamilton College',
'State': 'NY',
'Coach': 'Jean Raposa'},{'College': 'Hampshire College',
'State': 'MA',
'Coach': 'Katherine Roberts'},{'College': 'Hartwick College',
'State': 'NY',
'Coach': 'Tammy Sousa'},{'College': 'High Point University',
'State': 'NC',
'Coach': 'Catherine Schlaeppi'},{'College': 'Hillsdale College',
'State': 'MI',
'Coach': 'Danielle Cole'},{'College': 'Hiram College',
'State': 'OH',
'Coach': 'Christine Wokojance'},{'College': 'Hobart and William Smith Colleges',
'State': 'NY',
'Coach': 'Sarah Barge'},{'College': 'Hofstra University',
'State': 'NY',
'Coach': 'Deborah Rittereiser'},{'College': 'Hollins University',
'State': 'VA',
'Coach': 'Sandy Gerald'},{'College': 'Hood College',
'State': 'MD',
'Coach': 'Elizabeth Hummel'},{'College': 'Illinois State University',
'State': 'IL',
'Coach': 'Natalie Meza'},{'College': 'Indiana University',
'State': 'IN',
'Coach': 'Stephanie Laski'},{'College': 'Indiana University at South Bend',
'State': 'IN',
'Coach': 'Lindsay Rudd'},{'College': 'Indiana University East',
'State': 'IN',
'Coach': 'Kellie Riggott'},{'College': 'Indiana University of Pennsylvania',
'State': 'PA',
'Coach': 'Kara Hollabaugh'},{'College': 'IndianaUniversity Purdue University at Indianapolis',
'State': 'IN',
'Coach': 'Jessie Ann Bolash'},{'College': 'Iowa State University',
'State': 'IA',
'Coach': 'Lisa Kirk'},{'College': 'Ithaca College',
'State': 'NY',
'Coach': 'Audra Ravo'},{'College': 'James Madison University',
'State': 'VA',
'Coach': 'Briana Stone'},{'College': 'Johns Hopkins University',
'State': 'MD',
'Coach': 'Kathy Wells'},{'College': 'Johnson&Wales; University',
'State': 'RI',
'Coach': 'Dirk Fogg'},{'College': 'Judson College',
'State': 'AL',
'Coach': 'Jennifer Hoggle'},{'College': 'Kansas State University',
'State': 'KS',
'Coach': 'Ashley Duda'},{'College': 'Kennesaw State University',
'State': 'GA',
'Coach': 'Lucy Molinari'},{'College': 'Kent State University',
'State': 'OH',
'Coach': 'Redean Sheppard'},{'College': 'Kenyon College',
'State': 'OH',
'Coach': 'Erica Parnisari'},{'College': 'Keuka College',
'State': 'NY',
'Coach': 'Holly Bedient'},{'College': 'Knox College',
'State': 'IL',
'Coach': "Theresa O'Keefe"},{'College': 'Kutztown University',
'State': 'PA',
'Coach': 'Susan Casale'},{'College': 'Lafayette College',
'State': 'PA',
'Coach': 'Erin Githens'},{'College': 'Lake Erie College',
'State': 'OH',
'Coach': 'Mary Pardee'},{'College': 'Lake Forest College',
'State': 'IL',
'Coach': 'Dundee Bartlett'},{'College': 'Lakehead University',
'State': 'ON',
'Coach': 'Amanda Kine'},{'College': 'Lander University',
'State': 'SC',
'Coach': 'Marianne Bartley Lehman'},{'College': 'Laramie County Community College',
'State': 'WY',
'Coach': 'Lanae McDonald'},{'College': 'LaSalle University',
'State': 'PA',
'Coach': 'Amanda Enwright'},{'College': 'Le Moyne College',
'State': 'NY',
'Coach': 'Nicolle Madonna'},{'College': 'Lebanon Valley College',
'State': 'PA',
'Coach': 'Cheryl Keller'},{'College': 'Lehigh University',
'State': 'PA',
'Coach': 'Marisa Kalmar'},{'College': 'Lenoir Rhyne University',
'State': 'NC',
'Coach': 'Sarah Klassett'},{'College': 'Liberty University',
'State': 'VA',
'Coach': 'Jim Arrigon'},{'College': 'Linn-Benton Community College',
'State': 'OR',
'Coach': 'Dawn Salazar-Ross'},{'College': 'Long Island University -  Post',
'State': 'NY',
'Coach': 'Brooke Chasin'},{'College': 'Longwood University',
'State': 'VA',
'Coach': 'K.C. Meadows'},{'College': 'Louisiana State University',
'State': 'LA',
'Coach': 'Leaf Boswell'},{'College': 'Lycoming College',
'State': 'PA',
'Coach': 'Margaret Hervey'},{'College': 'Lynchburg College',
'State': 'VA',
'Coach': 'Mimi Wroten'},{'College': 'Marist College',
'State': 'NY',
'Coach': 'Clare Knapp'},{'College': 'Martin Community College',
'State': 'NC',
'Coach': 'Carey Stewart'},{'College': 'Mary Baldwin College',
'State': 'VA',
'Coach': 'Donal Oldaker'},{'College': 'Maryville College',
'State': 'TN',
'Coach': 'Christen Khym'},{'College': 'Mercyhurst College',
'State': 'PA',
'Coach': 'Halli Bidwell'},{'College': 'Miami University of Ohio',
'State': 'OH',
'Coach': 'Heather Pinnick'},{'College': 'Michigan State University',
'State': 'MI',
'Coach': 'Leesa Massman'},{'College': 'Middle Tennessee State University',
'State': 'TN',
'Coach': 'Anne Brzezicki'},{'College': 'Middlebury College',
'State': 'VT',
'Coach': 'Kate Selby'},{'College': 'Midway University',
'State': 'KY',
'Coach': 'Robin Gollehon'},{'College': 'Millersville University',
'State': 'PA',
'Coach': 'Heidi Douts'},{'College': 'Mississippi College',
'State': 'MS',
'Coach': 'Christina Davey'},{'College': 'Mississippi State University',
'State': 'MS',
'Coach': 'Ashley Shiffler'},{'College': 'Missouri State University',
'State': 'MO',
'Coach': 'Susan Webb'},{'College': 'Molloy College',
'State': 'NY',
'Coach': 'Carole Gerrity'},{'College': 'Montana State University',
'State': 'MT',
'Coach': 'Amy Morgan'},{'College': 'Montana State University Billings',
'State': 'MT',
'Coach': 'Robert Auch'},{'College': 'Moravian College',
'State': 'PA',
'Coach': 'Jessica Brittain'},{'College': 'Morehead State University',
'State': 'KY',
'Coach': 'Erin LeCompt'},{'College': 'Morrisville State College',
'State': 'NY',
'Coach': 'Erin Dunn'},{'College': 'Mount Holyoke College',
'State': 'MA',
'Coach': 'Carol (C. J.) Law'},{'College': 'Mount Ida College',
'State': 'MA',
'Coach': 'Mary Beth McGee'},{'College': 'Mt. San Antonio College',
'State': 'CA',
'Coach': 'Dawn Waters'},{'College': 'Mt. St. Mary's University',
'State': 'MD',
'Coach': 'Janis Groomes'},{'College': 'Murray State University',
'State': 'KY',
'Coach': 'Sue Robinson'},{'College': 'Nazareth College of Rochester',
'State': 'NY',
'Coach': 'Terese Bouchard'},{'College': 'New York University',
'State': 'NY',
'Coach': 'Ashton Phillips'},{'College': 'North Carolina State University',
'State': 'NC',
'Coach': 'Sara Conversano'},{'College': 'North Central Texas College',
'State': 'TX',
'Coach': 'Bill Kaven'},{'College': 'North Dakota State University',
'State': 'ND',
'Coach': 'Tara Swanson'},{'College': 'Northeastern Oklahoma A&M; College',
'State': 'OK',
'Coach': 'Amanda Burrows'},{'College': 'Northeastern University',
'State': 'MA',
'Coach': 'Ashley Pimentel'},{'College': 'Northern Arizona University',
'State': 'AZ',
'Coach': 'Julie Golden'},{'College': 'Northern Illinois University',
'State': 'IL',
'Coach': 'Joleen DeWitt'},{'College': 'Northern Kentucky University',
'State': 'KY',
'Coach': 'Lynlee Foster'},{'College': 'Northwestern University',
'State': 'IL',
'Coach': 'Sara Timmis'},{'College': 'Norwich University',
'State': 'VT',
'Coach': 'Rita Towne'},{'College': 'Nova Southeastern University',
'State': 'FL',
'Coach': 'Jackie George'},{'College': 'Oakland University',
'State': 'MI',
'Coach': 'Aimee Latsch'},{'College': 'Oberlin College',
'State': 'OH',
'Coach': 'Ric Weitzel'},{'College': 'Ohio State University',
'State': 'OH',
'Coach': 'Ollie Griffith'},{'College': 'Ohio University',
'State': 'OH',
'Coach': 'Karen Hiehle'},{'College': 'Ohio Wesleyan University',
'State': 'OH',
'Coach': 'Linda Dare'},{'College': 'Oklahoma Panhandle State University',
'State': 'OK',
'Coach': 'Malissa Meyer'},{'College': 'Old Dominion University',
'State': 'VA',
'Coach': 'Kasey Evans'},{'College': 'Oneonta State College',
'State': 'NY',
'Coach': 'Joycelyn Northup'},{'College': 'Oregon State University',
'State': 'OR',
'Coach': 'Dawn Ross'},{'College': 'Otterbein University',
'State': 'OH',
'Coach': 'Tenley Struhs'},{'College': 'Parkland College',
'State': 'IL',
'Coach': 'Megan Tyler'},{'College': 'Penn State Berks Equestrian Club',
'State': 'PA',
'Coach': 'Rebecca Weik'},{'College': 'Penn State Erie - The Behrend College',
'State': 'PA',
'Coach': 'Lew Trumble'},{'College': 'Penn State Harrisburg',
'State': 'PA',
'Coach': 'Alida Burkholder'},{'College': 'Penn State University',
'State': 'PA',
'Coach': 'Kerry Kocher'},{'College': 'Post University',
'State': 'CT',
'Coach': 'Justin Gregory'},{'College': 'Princeton University',
'State': 'NJ',
'Coach': 'Ashton Phillips'},{'College': 'Purdue University',
'State': 'IN',
'Coach': 'Gerald Steinmetz'},{'College': 'Purdue University Calumet',
'State': 'IN',
'Coach': 'Alexandra Moran'},{'College': 'Purdue University North Central',
'State': 'IN',
'Coach': 'Jennifer Turner'},{'College': 'Radford University',
'State': 'VA',
'Coach': 'Kimberly Huffman'},{'College': 'Randolph College',
'State': 'VA',
'Coach': 'Christopher Mitchell'},{'College': 'Randolph-Macon College',
'State': 'VA',
'Coach': 'John West'},{'College': 'Redlands Community College',
'State': 'OK',
'Coach': 'Dedra Baker'},{'College': 'Reedley College',
'State': 'CA',
'Coach': 'christina marin'},{'College': 'Rensselaer Polytechnic Institute',
'State': 'NY',
'Coach': 'Megan Rogers'},{'College': 'Rhode Island College',
'State': 'RI',
'Coach': 'Dana Stark'},{'College': 'Rice University',
'State': 'TX',
'Coach': 'Cathy Strobel'},{'College': 'Rider University',
'State': 'NJ',
'Coach': 'Andrea Hart-Sagolla'},{'College': 'Ripon College',
'State': 'WI',
'Coach': 'Mary Avery'},{'College': 'Roanoke College',
'State': 'VA',
'Coach': 'Carolyn Williams'},{'College': 'Rochester Institute of Technology',
'State': 'NY',
'Coach': 'Gail Miller'},{'College': 'Rocky Mountain College',
'State': 'MT',
'Coach': 'Chris Brown'},{'College': 'Roger Williams University',
'State': 'RI',
'Coach': 'Ted Torrey'},{'College': 'Rollins College',
'State': 'FL',
'Coach': 'Suzanne Muchow'},{'College': 'Rowan University',
'State': 'NJ',
'Coach': 'Ariel Frattaroli'},{'College': 'Rutgers University',
'State': 'NJ',
'Coach': 'Kelly Lamont-Francfort'},{'College': 'Sacred Heart University',
'State': 'CT',
'Coach': 'Tiffany Hajdasz'},{'College': 'Saginaw Valley State University',
'State': 'MI',
'Coach': 'Nancy Bellor'},{'College': 'Saint Leo University',
'State': 'FL',
'Coach': 'Grant Pennington'},{'College': 'Saint Louis University',
'State': 'MO',
'Coach': 'Jodi Gold'},{'College': 'Saint Mary's College',
'State': 'IN',
'Coach': 'Julie Harnish'},{'College': 'Saint Vincent College',
'State': 'PA',
'Coach': 'Veronica Ent'},{'College': 'Salem College',
'State': 'NC',
'Coach': 'Michelle Hargreaves'},{'College': 'Salisbury University',
'State': 'MD',
'Coach': 'Amy Walls'},{'College': 'Salve  Regina University',
'State': 'RI',
'Coach': 'Patrick March'},{'College': 'Santa Clara University',
'State': 'CA',
'Coach': 'Nicole Abercrombie'},{'College': 'Sarah Lawrence College',
'State': 'NY',
'Coach': 'Lori Rakoczy'},{'College': 'Savannah College of Art and Design',
'State': 'GA',
'Coach': 'Ashley Henry'},{'College': 'Seton Hill University',
'State': 'PA',
'Coach': 'Rebecca Bloom'},{'College': 'Shippensburg University',
'State': 'PA',
'Coach': 'Mary Bast'},{'College': 'Siena College',
'State': 'NY',
'Coach': 'Nora Hanlon'},{'College': 'Skidmore College',
'State': 'NY',
'Coach': 'Cindy Ford'},{'College': 'Slippery Rock University',
'State': 'PA',
'Coach': 'Amy Keefer'},{'College': 'Smith College',
'State': 'MA',
'Coach': 'Suzanne Payne'},{'College': 'Sonoma State University',
'State': 'CA',
'Coach': 'Michelle Davis'},{'College': 'Southeast Missouri State University',
'State': 'MO',
'Coach': 'SuAnne Remley'},{'College': 'Southern Illinois University Carbondale',
'State': 'IL',
'Coach': "Jill O'Donoghue"},{'College': 'Southern Nazarene University',
'State': 'OK',
'Coach': 'Natalie Freeman'},{'College': 'Springfield College',
'State': 'MA',
'Coach': 'Dani Corkill'},{'College': 'St Cloud State University',
'State': 'MN',
'Coach': 'Samantha Cotter'},{'College': 'St. Andrews University',
'State': 'NC',
'Coach': 'Peggy McElveen'},{'College': 'St. Joseph's College',
'State': 'NY',
'Coach': 'sheila Rodgers'},{'College': 'St. Lawrence University',
'State': 'NY',
'Coach': 'Mary Drueding'},{'College': 'St. Mary-of-the-Woods College',
'State': 'IN',
'Coach': 'Sara Schulz'},{'College': 'St. Marys College of Maryland',
'State': 'MD',
'Coach': 'Leslie Allen'},{'College': 'Stanford University',
'State': 'CA',
'Coach': 'Vanessa Bartsch'},{'College': 'State University of New York at New Paltz',
'State': 'NY',
'Coach': 'Susan Clark'},{'College': 'State University of New York at Oswego',
'State': 'NY',
'Coach': 'Jillian Bergstresser'},{'College': 'Stetson University',
'State': 'FL',
'Coach': 'Beth Collier'},{'College': 'Stevens Institute of Technology',
'State': 'NJ',
'Coach': 'Patti Zwaan'},{'College': 'Stockton University',
'State': 'NJ',
'Coach': 'Stephanie Morrongiello'},{'College': 'Stonehill College',
'State': 'MA',
'Coach': 'kristen redquest'},{'College': 'Stony Brook University',
'State': 'NY',
'Coach': 'Myrna Treuting'},{'College': 'Suffolk County Community College',
'State': 'NY',
'Coach': 'deborah rittereiser'},{'College': 'SUNY Albany',
'State': 'NY',
'Coach': 'Tracy James-Pedersen'},{'College': 'SUNY Cobleskill',
'State': 'NY',
'Coach': 'Ray Whelihan'},{'College': 'SUNY Geneseo',
'State': 'NY',
'Coach': 'Kim Sanford'},{'College': 'Susquehanna University',
'State': 'PA',
'Coach': 'Jan Phillips'},{'College': 'Sweet Briar College',
'State': 'VA',
'Coach': 'Mimi Wroten'},{'College': 'Syracuse University',
'State': 'NY',
'Coach': 'Denise Van Patten'},{'College': 'Tarleton State University',
'State': 'TX',
'Coach': 'Annie Penrice'},{'College': 'Taylor University',
'State': 'IN',
'Coach': 'Margaret Boyle'},{'College': 'Temple University',
'State': 'PA',
'Coach': 'Jenn Post'},{'College': 'Tennessee Tech University',
'State': 'TN',
'Coach': 'Becky Huddleston'},{'College': 'Texas A&M; University-Commerce',
'State': 'TX',
'Coach': 'Brooke Harris'},{'College': 'Texas State University-San Marcos',
'State': 'TX',
'Coach': 'Katherine Deichmann'},{'College': 'Texas Tech University',
'State': 'TX',
'Coach': 'Lindsey Jones'},{'College': 'The University of Akron',
'State': 'OH',
'Coach': 'Laura Hearty'},{'College': 'The University of Oklahoma',
'State': 'OK',
'Coach': 'Laura Hoover'},{'College': 'The University of the South',
'State': 'TN',
'Coach': 'Allie Truitt'},{'College': 'Thiel College',
'State': 'PA',
'Coach': 'Jenna Malnar'},{'College': 'Tiffin Univeristy',
'State': 'OH',
'Coach': 'Julie Vogel'},{'College': 'Towson University',
'State': 'MD',
'Coach': 'Sandy Weinreich'},{'College': 'Transylvania University',
'State': 'KY',
'Coach': 'Tanya Davis'},{'College': 'Trinity College',
'State': 'CT',
'Coach': 'Amy Kriwitsky'},{'College': 'Trinity University',
'State': 'TX',
'Coach': 'Stephanie Cook'},{'College': 'Truman State University',
'State': 'MO',
'Coach': 'Emily Costello'},{'College': 'Tufts University',
'State': 'MA',
'Coach': 'Shane Powell'},{'College': 'Tulane University',
'State': 'LA',
'Coach': 'Kristen Swope'},{'College': 'U.S. Air Force Academy',
'State': 'CO',
'Coach': 'Allyson Hartenburg'},{'College': 'UNC-Chapel Hill',
'State': 'NC',
'Coach': 'Courtney Clayton'},{'College': 'Union College',
'State': 'NY',
'Coach': 'peggy aedjian'},{'College': 'United States Military Academy',
'State': 'NY',
'Coach': 'Peter and Sherry Cashman'},{'College': 'University at Buffalo',
'State': 'NY',
'Coach': 'Beth Walkowicz'},{'College': 'University of Alabama',
'State': 'AL',
'Coach': 'Ashley Morrison'},{'College': 'University of Arizona',
'State': 'AZ',
'Coach': 'Sheryl Gonnsen'},{'College': 'University of British Columbia',
'State': 'BC',
'Coach': 'Katrina Per'},{'College': 'University of California San Diego',
'State': 'CA',
'Coach': 'Mark Conley'},{'College': 'University of California, Berkeley',
'State': 'CA',
'Coach': 'Diane Yeager'},{'College': 'University of California, Davis',
'State': 'CA',
'Coach': 'Ryan Oropeza'},{'College': 'University of California, Los Angeles',
'State': 'CA',
'Coach': 'Carolin Malmkvist'},{'College': 'University of California, Santa Cruz',
'State': 'CA',
'Coach': 'Cassie Belmont'},{'College': 'University of California: Santa Barbara',
'State': 'CA',
'Coach': 'Alanna Snowden'},{'College': 'University of Central Florida',
'State': 'FL',
'Coach': 'Lesli Isaacson'},{'College': 'University of Cincinnati',
'State': 'OH',
'Coach': 'Missy Jo Hollingsworth'},{'College': 'University of Colorado - Colorado Springs',
'State': 'CO',
'Coach': 'Tracey Powers'},{'College': 'University of Colorado, Boulder',
'State': 'CO',
'Coach': 'Jill Pelzel'},{'College': 'University of Connecticut',
'State': 'CT',
'Coach': 'Alena Meacham'},{'College': 'University of Delaware',
'State': 'DE',
'Coach': 'Whitney Carmouche'},{'College': 'University of Findlay',
'State': 'OH',
'Coach': 'Cindy Morehead'},{'College': 'University of Florida',
'State': 'FL',
'Coach': 'Kim Burnette'},{'College': 'University of Georgia',
'State': 'GA',
'Coach': 'Katie Poteet'},{'College': 'University of Guelph',
'State': 'ON',
'Coach': 'Amy Noonan'},{'College': 'University Of Illinois at Urbana-Champaign',
'State': 'IL',
'Coach': 'Teresa (Terri) Foreman'},{'College': 'University of Kansas',
'State': 'KS',
'Coach': 'Elizabeth Gravatt'},{'College': 'University of Kentucky',
'State': 'KY',
'Coach': 'Diana Conlon'},{'College': 'University of Louisville',
'State': 'KY',
'Coach': 'Sarah Younger'},{'College': 'University of Maine',
'State': 'ME',
'Coach': 'Gail McCormack'},{'College': 'University of Mary Washington',
'State': 'VA',
'Coach': 'Teresa Seay'},{'College': 'University of Maryland',
'State': 'MD',
'Coach': 'Astrid Dalley'},{'College': 'University of Maryland, Baltimore County',
'State': 'MD',
'Coach': 'Sherri Trenary'},{'College': 'University of Massachusetts at Amherst',
'State': 'MA',
'Coach': 'Jillianne Smith'},{'College': 'University of Massachusetts Dartmouth',
'State': 'MA',
'Coach': 'Mary Charette'},{'College': 'University of Miami',
'State': 'FL',
'Coach': 'Karen Flynn'},{'College': 'University of Michigan',
'State': 'MI',
'Coach': 'Jennifer Blades'},{'College': 'University of Minnesota, Crookston',
'State': 'MN',
'Coach': 'Kayla Krueger'},{'College': 'University of Minnesota-Twin Cities',
'State': 'MN',
'Coach': 'Jamie Moeller'},{'College': 'University of Mississippi (Ole Miss)',
'State': 'MS',
'Coach': 'Gene (Beanie) Cone'},{'College': 'University of Montana',
'State': 'MT',
'Coach': 'Stephanie Kappes'},{'College': 'University of Montana Western',
'State': 'MT',
'Coach': 'Emelia Jones'},{'College': 'University of Nebraska-Lincoln',
'State': 'NE',
'Coach': 'Lori Jaixen'},{'College': 'University of New England',
'State': 'ME',
'Coach': 'Jackie Blackwell'},{'College': 'University of New Hampshire',
'State': 'NH',
'Coach': 'Christina Keim'},{'College': 'University of North Alabama',
'State': 'AL',
'Coach': 'Amy Smith'},{'College': 'University of North Carolina at Asheville',
'State': 'NC',
'Coach': 'Briana Ambrosic'},{'College': 'University of North Carolina at Charlotte',
'State': 'NC',
'Coach': 'Chelsea Dressler'},{'College': 'University of North Carolina Wilmington',
'State': 'NC',
'Coach': 'Lauryn Wiser'},{'College': 'University of North Carolina-Greensboro',
'State': 'NC',
'Coach': 'Allison Townley'},{'College': 'University of North Florida',
'State': 'FL',
'Coach': 'Julie Steinmetz-Usoff'},{'College': 'University of North Georgia',
'State': 'GA',
'Coach': 'Amanda Garner'},{'College': 'University of North Texas',
'State': 'TX',
'Coach': 'Courtney Burggren'},{'College': 'University of Notre Dame / Saint Mary's College',
'State': 'IN',
'Coach': 'Kerry Hilgendorf'},{'College': 'University of Oregon',
'State': 'OR',
'Coach': 'Courtney Horan'},{'College': 'University of Ottawa',
'State': 'ON',
'Coach': 'Mark Struthers'},{'College': 'University of Pennsylvania',
'State': 'PA',
'Coach': 'Dawne Morrone'},{'College': 'University of Pittsburgh',
'State': 'PA',
'Coach': 'James Boyce'},{'College': 'University of Rhode Island',
'State': 'RI',
'Coach': 'Wendy Brayman'},{'College': 'University of Richmond',
'State': 'VA',
'Coach': 'Jessica Boppe'},{'College': 'University of Rochester',
'State': 'NY',
'Coach': 'Peggy Gauger'},{'College': 'University of San Diego',
'State': 'CA',
'Coach': 'Alison Mundo'},{'College': 'University of Scranton',
'State': 'PA',
'Coach': 'Tara Lane Waitkus'},{'College': 'University of South Carolina',
'State': 'SC',
'Coach': 'Angela MacFawn'},{'College': 'University of South Carolina Aiken',
'State': 'SC',
'Coach': 'John Abbott'},{'College': 'University of South Florida',
'State': 'FL',
'Coach': 'Lauren Barth'},{'College': 'University of Southern California',
'State': 'CA',
'Coach': 'Kathryn Griffiths'},{'College': 'University of Tampa',
'State': 'FL',
'Coach': "Sherri O'Connor"},{'College': 'University of Tennessee - Knoxville',
'State': 'TN',
'Coach': 'Lacey Johnston'},{'College': 'University of Texas at Austin',
'State': 'TX',
'Coach': 'Sydney Kornman'},{'College': 'University of Vermont',
'State': 'VT',
'Coach': 'Madeleine Austin'},{'College': 'University of Virginia',
'State': 'VA',
'Coach': 'Claiborne Bishop'},{'College': 'University of Washington',
'State': 'WA',
'Coach': 'Aidan Beaton'},{'College': 'University of West Florida',
'State': 'FL',
'Coach': 'Sierra Smallwood'},{'College': 'University of Western Ontario',
'State': 'ON',
'Coach': 'Hilary Rock'},{'College': 'University of Wisconsin - Eau Claire',
'State': 'WI',
'Coach': 'Tammy Olson'},{'College': 'University of Wisconsin-La Crosse',
'State': 'WI',
'Coach': 'Christy Lowell'},{'College': 'University of Wisconsin-Madison',
'State': 'WI',
'Coach': 'Mark Aplin'},{'College': 'University of Wisconsin-Milwaukee',
'State': 'WI',
'Coach': 'Lisa Behling'},{'College': 'University of Wisconsin-Platteville',
'State': 'WI',
'Coach': 'Mathea Durica'},{'College': 'University of Wisconsin-River Falls',
'State': 'WI',
'Coach': 'Peter RAYNE'},{'College': 'University of Wyoming',
'State': 'WY',
'Coach': 'Jessica Ford'},{'College': 'Utah State University',
'State': 'UT',
'Coach': 'Jason Romney'},{'College': 'Valley Forge Military College',
'State': 'PA',
'Coach': 'Sara McCoy Palmer'},{'College': 'Vanderbilt University',
'State': 'TN',
'Coach': 'Janelle Harcus'},{'College': 'Vassar College',
'State': 'NY',
'Coach': 'Michelle Clopp'},{'College': 'Villanova University',
'State': 'PA',
'Coach': 'Sara McCoy'},{'College': 'Virginia Commonwealth University',
'State': 'VA',
'Coach': 'Sulu Rose Reed'},{'College': 'Virginia Tech',
'State': 'VA',
'Coach': 'Sherri West'},{'College': 'Wake Forest University',
'State': 'NC',
'Coach': 'Michelle Hargreaves'},{'College': 'Washington & Jefferson College',
'State': 'PA',
'Coach': 'Olivia DeCesar'},{'College': 'Washington and Lee University',
'State': 'VA',
'Coach': 'Gordon Reistrup'},{'College': 'Washington College',
'State': 'MD',
'Coach': 'Chris Bigelow'},{'College': 'Washington State University',
'State': 'WA',
'Coach': 'Katharina Whetzel'},{'College': 'Washington University in St. Louis',
'State': 'MO',
'Coach': 'Patti Boland'},{'College': 'Wellesley College',
'State': 'MA',
'Coach': 'Alli Mitchell'},{'College': 'Wesleyan College',
'State': 'GA',
'Coach': 'Jessica Denniston'},{'College': 'Wesleyan University',
'State': 'CT',
'Coach': 'Armand Chenelle'},{'College': 'West Chester University',
'State': 'PA',
'Coach': 'Wendy Myers'},{'College': 'West Texas A&M; University',
'State': 'TX',
'Coach': 'Amanda Love'},{'College': 'West Virginia University',
'State': 'WV',
'Coach': 'Bobby Dean'},{'College': 'Western Carolina University',
'State': 'NC',
'Coach': 'Angela Fowler'},{'College': 'Western Illinois University',
'State': 'IL',
'Coach': 'kayla weikert'},{'College': 'Western Kentucky University',
'State': 'KY',
'Coach': 'CHARLES ANDERSON'},{'College': 'Western Michigan University',
'State': 'MI',
'Coach': 'Rob Stewart'},{'College': 'Western Washington University',
'State': 'WA',
'Coach': 'Ashley Greyell'},{'College': 'Westfield State University',
'State': 'MA',
'Coach': 'Frances Cross'},{'College': 'Westminster College',
'State': 'PA',
'Coach': 'Janet Rowan'},{'College': 'Wheaton College',
'State': 'MA',
'Coach': 'Carly Fisher'},{'College': 'Whittier College',
'State': 'CA',
'Coach': 'Patty Foltz Mccarty'},{'College': 'William Paterson University',
'State': 'NJ',
'Coach': 'Hayley Rooney'},{'College': 'Williams College',
'State': 'MA',
'Coach': 'Lisa DeMayo'},{'College': 'Wilmington College',
'State': 'OH',
'Coach': 'Jennifer Riddle'},{'College': 'Wilson College',
'State': 'PA',
'Coach': 'Megan Mendenhall'},{'College': 'Wofford College',
'State': 'SC',
'Coach': 'Jeanne Smith'},{'College': 'Worcester State University',
'State': 'MA',
'Coach': 'Tamara Johnston'},{'College': 'Xavier University',
'State': 'OH',
'Coach': 'Maria Kneipp'},{'College': 'Yale University',
'State': 'CT',
'Coach': 'Jennifer Thompson'},{'College': 'Youngstown State University',
'State': 'OH',
'Coach': 'Amy Watkins'},]