schools_list = [{"School":"Adelphi  University","State":"NY","Coach":"Jennifer Henick"},
{"School":"Adrian College","State":"MI","Coach":"Jaclynn Gray"},
{"School":"Albion College","State":"MI","Coach":"Randi Gardner"},
{"School":"Alfred State College","State":"NY","Coach":"Victoria Bolton"},
{"School":"Alfred University","State":"NY","Coach":"Nancy Kohler"},
{"School":"Allegheny College","State":"PA","Coach":"Halli Bidwell"},
{"School":"Alma College","State":"MI","Coach":"Emily Pittman"},
{"School":"American University","State":"DC","Coach":"Star Dalley"},
{"School":"Amherst College","State":"MA","Coach":"Beth Manning"},
{"School":"Appalachian State University","State":"NC","Coach":"Sarah Klassett"},
{"School":"Arcadia University","State":"PA","Coach":"Amber Jewell"},
{"School":"Arizona State University","State":"AZ","Coach":"Rachel Jansen"},
{"School":"Assumption College","State":"MA","Coach":"Joy Sigona"},
{"School":"Auburn University","State":"AL","Coach":"Lisa Dorsey"},
{"School":"Augustana College","State":"IL","Coach":"Julie Mann"},
{"School":"Ave Maria University","State":"FL","Coach":"Katie O'Hare"},
{"School":"Averett University","State":"VA","Coach":"Cricket Stone"},
{"School":"Ball State University","State":"IN","Coach":"Tammie Jones"},
{"School":"Bard College","State":"NY","Coach":"Sharon Bach"},
{"School":"Bates College","State":"ME","Coach":"Stephanie Plaisted"},
{"School":"Becker College","State":"MA","Coach":"Nicole Eastman"},
{"School":"Belmont University","State":"TN","Coach":"Beth Bankemper"},
{"School":"Bennington College","State":"VT","Coach":"Tara Lowary"},
{"School":"Bentley University","State":"MA","Coach":"Melissa Consalvo"},
{"School":"Berry College","State":"GA","Coach":"Margaret Knight"},
{"School":"Bethany College","State":"WV","Coach":"Beth Johnson"},
{"School":"Binghamton University","State":"NY","Coach":"Mary Celeste Penfield"},
{"School":"Black Hawk College","State":"IL","Coach":"Donna Irvin"},
{"School":"Bloomsburg University","State":"PA","Coach":"Amie Wolfinger"},
{"School":"Boston College","State":"MA","Coach":"Sheila Dunham"},
{"School":"Boston University","State":"MA","Coach":"Phyllis Cervelli"},
{"School":"Bowdoin College","State":"ME","Coach":"Virginia Shaw"},
{"School":"Bowling Green State University","State":"OH","Coach":"Jill Jewett"},
{"School":"Brandeis University","State":"MA","Coach":"Katie Bobola"},
{"School":"Bridgewater College","State":"VA","Coach":"Jerry Schurink"},
{"School":"Bridgewater State University","State":"MA","Coach":"Geraldine Burnet"},
{"School":"Brock University","State":"ON","Coach":"Shara Pavan"},
{"School":"Brockport College","State":"NY","Coach":"Jolene Hasseler"},
{"School":"Brown University","State":"RI","Coach":"Michaela Scanlon"},
{"School":"Bucknell University","State":"PA","Coach":"Farra Phillips-Hillyard"},
{"School":"Bucks County Community College","State":"PA","Coach":"Patricia Silcox"},
{"School":"Butler University","State":"IN","Coach":"Dawn Stumm"},
{"School":"Cal Poly State University, San Luis Obispo","State":"CA","Coach":"Natalie Baker"},
{"School":"California State Polytechnic University Pomona","State":"CA","Coach":"Marissa Shotwell-Tabke"},
{"School":"California State University, Fullerton","State":"CA","Coach":"Mercedes Hanson"},
{"School":"California University of Pennsylvania","State":"PA","Coach":"Susan Malencia"},
{"School":"Calvin College","State":"MI","Coach":"Kris McAfee"},
{"School":"Campbell University","State":"NC","Coach":"Michelle Stephenson"},
{"School":"Canisius College","State":"NY","Coach":"Judy West"},
{"School":"Case Western Reserve University","State":"OH","Coach":"Allison Park"},
{"School":"Castleton University","State":"VT","Coach":"Judy O'Rourke"},
{"School":"Cazenovia College","State":"NY","Coach":"Amy Sherrick-von Schiller"},
{"School":"Centenary College","State":"NJ","Coach":"Heather Clark"},
{"School":"Central Connecticut State University","State":"CT","Coach":"Kayla Blanchette"},
{"School":"Central Michigan University","State":"MI","Coach":"Melanie Blues"},
{"School":"Central Washington University","State":"WA","Coach":"Tessa Churchill"},
{"School":"Chapman University","State":"CA","Coach":"Jessica Bower"},
{"School":"Chestnut Hill College","State":"PA","Coach":"Amanda Enwright"},
{"School":"Christopher Newport University","State":"VA","Coach":"Ryann Winn"},
{"School":"Claremont Colleges","State":"CA","Coach":"Mercedes Hanson"},
{"School":"Clarion University Venango Campus","State":"PA","Coach":"Tammy Braham"},
{"School":"Clark University","State":"MA","Coach":"Sarah Grogan"},
{"School":"Clemson University","State":"SC","Coach":"Rebecca Shirley"},
{"School":"Coastal Carolina University","State":"SC","Coach":"Kristina Crumlish"},
{"School":"Colby Community College","State":"KS","Coach":"Shanda Mattix"},
{"School":"Colby Sawyer College","State":"NH","Coach":"Pamela Payson"},
{"School":"Colgate University","State":"NY","Coach":"Anna Hackney"},
{"School":"College of Central Florida","State":"FL","Coach":"Judy Downer"},
{"School":"College of Charleston","State":"SC","Coach":"Robert Story"},
{"School":"College of the Holy Cross","State":"MA","Coach":"Frank Perla"},
{"School":"College of the Sequoias","State":"CA","Coach":"Kim Pitigliano"},
{"School":"College Of William And Mary","State":"VA","Coach":"Karen Greenwood"},
{"School":"College Of Wooster","State":"OH","Coach":"Karla Forrer"},
{"School":"Colorado College","State":"CO","Coach":"Tracey Powers"},
{"School":"Colorado Northwestern Community College","State":"CO","Coach":"Miranda Morris"},
{"School":"Colorado School of Mines","State":"CO","Coach":"Jennifer Duffy"},
{"School":"Colorado State University","State":"CO","Coach":"Kathy Montgomery"},
{"School":"Columbia University","State":"NY","Coach":"Penny Kinnally"},
{"School":"Connecticut College","State":"CT","Coach":"Richard Luckhardt"},
{"School":"Converse College","State":"SC","Coach":"Lincoln Russell"},
{"School":"Cornell University","State":"NY","Coach":"Joanna Novakovic"},
{"School":"Curry College","State":"MA","Coach":"Jennifer Sullivan"},
{"School":"Dartmouth College","State":"NH","Coach":"Sally Batton"},
{"School":"Delaware Valley University","State":"PA","Coach":"Cory Kieschnick"},
{"School":"Denison University","State":"OH","Coach":"Claudia Hutchinson"},
{"School":"DeSales University","State":"PA","Coach":"Alexis Wirth"},
{"School":"Dickinson College","State":"PA","Coach":"Lindsay Vulich"},
{"School":"Drew University","State":"NJ","Coach":"Karen Sykes"},
{"School":"Drexel University","State":"PA","Coach":"Elizabeth Orem"},
{"School":"Duke University","State":"NC","Coach":"Virginia Rollins"},
{"School":"Duquesne University","State":"PA","Coach":"Linda Stevens"},
{"School":"Earlham College","State":"IN","Coach":"Kellie Riggott"},
{"School":"East Carolina University","State":"NC","Coach":"Caroline Jackson"},
{"School":"East Stroudsburg University","State":"PA","Coach":"Pat Speziale"},
{"School":"Eastern Illinois University","State":"IL","Coach":"Kandi Lane"},
{"School":"Edinboro University of Pennsylvania","State":"PA","Coach":"Lew Trumble"},
{"School":"Ellsworth Community College","State":"IA","Coach":"Lisa Jorgensen"},
{"School":"Elmira College","State":"NY","Coach":"MaryLou Spencer"},
{"School":"Elon University","State":"NC","Coach":"Anne Morgan"},
{"School":"Emory & Henry College","State":"VA","Coach":"Heather McCloud"},
{"School":"Emory University","State":"GA","Coach":"Robyn Sonis"},
{"School":"Endicott College","State":"MA","Coach":"Bethany Jones"},
{"School":"Fairfield University","State":"CT","Coach":"Naomi Gauruder"},
{"School":"Ferris State University","State":"MI","Coach":"Brianna Slager"},
{"School":"Ferrum College","State":"VA","Coach":"Margaret Cornwell"},
{"School":"Florida Atlantic University","State":"FL","Coach":"Tricia Carron"},
{"School":"Florida Gulf Coast University","State":"FL","Coach":"Roger Seitzmeir"},
{"School":"Florida International University","State":"FL","Coach":"Daniela Roy"},
{"School":"Florida Southern College","State":"FL","Coach":"Shannon Morrell"},
{"School":"Florida State University","State":"FL","Coach":"Jean Anthony"},
{"School":"Franciscan University","State":"OH","Coach":"Marissa Gump"},
{"School":"Franklin and Marshall College","State":"PA","Coach":"Gillian Beale King"},
{"School":"Furman University","State":"SC","Coach":"Leslie Huffman"},
{"School":"George Mason University","State":"VA","Coach":"Sue Buscher"},
{"School":"George Washington University","State":"MD","Coach":"Cindy Newberry"},
{"School":"Georgetown College","State":"KY","Coach":"Nori Scheffel"},
{"School":"Georgetown University","State":"DC","Coach":"Jeffrey Becker"},
{"School":"Georgia College and State University","State":"GA","Coach":"Carly Hunter"},
{"School":"Georgia Institute of Technology","State":"GA","Coach":"Emily Tomlinson"},
{"School":"Georgia Southern University","State":"GA","Coach":"Eleanor Ellis"},
{"School":"Georgia State University","State":"GA","Coach":"Karen Kerby"},
{"School":"Gettysburg College","State":"PA","Coach":"Janis Groomes"},
{"School":"Goucher College","State":"MD","Coach":"Jennifer Bunty"},
{"School":"Grand Valley State University","State":"MI","Coach":"Kris McAfee"},
{"School":"Grove City College","State":"PA","Coach":"Tammy Braham"},
{"School":"Gustavus Adolphus College","State":"MN","Coach":"Lauren Wood"},
{"School":"Gwynedd-Mercy College","State":"PA","Coach":"Amanda Enwright"},
{"School":"Hamilton College","State":"NY","Coach":"Jean Raposa"},
{"School":"Hampshire College","State":"MA","Coach":"Katherine Roberts"},
{"School":"Hartwick College","State":"NY","Coach":"Tammy Sousa"},
{"School":"High Point University","State":"NC","Coach":"Catherine Schlaeppi"},
{"School":"Hillsdale College","State":"MI","Coach":"Danielle Cole"},
{"School":"Hiram College","State":"OH","Coach":"Christine Wokojance"},
{"School":"Hobart and William Smith Colleges","State":"NY","Coach":"Sarah Barge"},
{"School":"Hofstra University","State":"NY","Coach":"Deborah Rittereiser"},
{"School":"Hollins University","State":"VA","Coach":"Sandy Gerald"},
{"School":"Hood College","State":"MD","Coach":"Elizabeth Hummel"},
{"School":"Illinois State University","State":"IL","Coach":"Natalie Meza"},
{"School":"Indiana University","State":"IN","Coach":"Stephanie Laski"},
{"School":"Indiana University at South Bend","State":"IN","Coach":"Lindsay Rudd"},
{"School":"Indiana University East","State":"IN","Coach":"Kellie Riggott"},
{"School":"Indiana University of Pennsylvania","State":"PA","Coach":"Kara Hollabaugh"},
{"School":"IndianaUniversity Purdue University at Indianapolis","State":"IN","Coach":"Jessie Ann Bolash"},
{"School":"Iowa State University","State":"IA","Coach":"Lisa Kirk"},
{"School":"Ithaca College","State":"NY","Coach":"Audra Ravo"},
{"School":"James Madison University","State":"VA","Coach":"Briana Stone"},
{"School":"Johns Hopkins University","State":"MD","Coach":"Kathy Wells"},
{"School":"Johnson&Wales; University","State":"RI","Coach":"Dirk Fogg"},
{"School":"Judson College","State":"AL","Coach":"Jennifer Hoggle"},
{"School":"Kansas State University","State":"KS","Coach":"Ashley Duda"},
{"School":"Kennesaw State University","State":"GA","Coach":"Lucy Molinari"},
{"School":"Kent State University","State":"OH","Coach":"Redean Sheppard"},
{"School":"Kenyon College","State":"OH","Coach":"Erica Parnisari"},
{"School":"Keuka College","State":"NY","Coach":"Holly Bedient"},
{"School":"Knox College","State":"IL","Coach":"Theresa O'Keefe"},
{"School":"Kutztown University","State":"PA","Coach":"Susan Casale"},
{"School":"Lafayette College","State":"PA","Coach":"Erin Githens"},
{"School":"Lake Erie College","State":"OH","Coach":"Mary Pardee"},
{"School":"Lake Forest College","State":"IL","Coach":"Dundee Bartlett"},
{"School":"Lakehead University","State":"ON","Coach":"Amanda Kine"},
{"School":"Lander University","State":"SC","Coach":"Marianne Bartley Lehman"},
{"School":"Laramie County Community College","State":"WY","Coach":"Lanae McDonald"},
{"School":"LaSalle University","State":"PA","Coach":"Amanda Enwright"},
{"School":"Le Moyne College","State":"NY","Coach":"Nicolle Madonna"},
{"School":"Lebanon Valley College","State":"PA","Coach":"Cheryl Keller"},
{"School":"Lehigh University","State":"PA","Coach":"Marisa Kalmar"},
{"School":"Lenoir Rhyne University","State":"NC","Coach":"Sarah Klassett"},
{"School":"Liberty University","State":"VA","Coach":"Jim Arrigon"},
{"School":"Linn-Benton Community College","State":"OR","Coach":"Dawn Salazar-Ross"},
{"School":"Long Island University -  Post","State":"NY","Coach":"Brooke Chasin"},
{"School":"Longwood University","State":"VA","Coach":"K.C. Meadows"},
{"School":"Louisiana State University","State":"LA","Coach":"Leaf Boswell"},
{"School":"Lycoming College","State":"PA","Coach":"Margaret Hervey"},
{"School":"Lynchburg College","State":"VA","Coach":"Mimi Wroten"},
{"School":"Marist College","State":"NY","Coach":"Clare Knapp"},
{"School":"Martin Community College","State":"NC","Coach":"Carey Stewart"},
{"School":"Mary Baldwin College","State":"VA","Coach":"Donal Oldaker"},
{"School":"Maryville College","State":"TN","Coach":"Christen Khym"},
{"School":"Mercyhurst College","State":"PA","Coach":"Halli Bidwell"},
{"School":"Miami University of Ohio","State":"OH","Coach":"Heather Pinnick"},
{"School":"Michigan State University","State":"MI","Coach":"Leesa Massman"},
{"School":"Middle Tennessee State University","State":"TN","Coach":"Anne Brzezicki"},
{"School":"Middlebury College","State":"VT","Coach":"Kate Selby"},
{"School":"Midway University","State":"KY","Coach":"Robin Gollehon"},
{"School":"Millersville University","State":"PA","Coach":"Heidi Douts"},
{"School":"Mississippi College","State":"MS","Coach":"Christina Davey"},
{"School":"Mississippi State University","State":"MS","Coach":"Ashley Shiffler"},
{"School":"Missouri State University","State":"MO","Coach":"Susan Webb"},
{"School":"Molloy College","State":"NY","Coach":"Carole Gerrity"},
{"School":"Montana State University","State":"MT","Coach":"Amy Morgan"},
{"School":"Montana State University Billings","State":"MT","Coach":"Robert Auch"},
{"School":"Moravian College","State":"PA","Coach":"Jessica Brittain"},
{"School":"Morehead State University","State":"KY","Coach":"Erin LeCompt"},
{"School":"Morrisville State College","State":"NY","Coach":"Erin Dunn"},
{"School":"Mount Holyoke College","State":"MA","Coach":"Carol (C. J.) Law"},
{"School":"Mount Ida College","State":"MA","Coach":"Mary Beth McGee"},
{"School":"Mt. San Antonio College","State":"CA","Coach":"Dawn Waters"},
{"School":"Mt. St. Mary's University","State":"MD","Coach":"Janis Groomes"},
{"School":"Murray State University","State":"KY","Coach":"Sue Robinson"},
{"School":"Nazareth College of Rochester","State":"NY","Coach":"Terese Bouchard"},
{"School":"New York University","State":"NY","Coach":"Ashton Phillips"},
{"School":"North Carolina State University","State":"NC","Coach":"Sara Conversano"},
{"School":"North Central Texas College","State":"TX","Coach":"Bill Kaven"},
{"School":"North Dakota State University","State":"ND","Coach":"Tara Swanson"},
{"School":"Northeastern Oklahoma A&M; College","State":"OK","Coach":"Amanda Burrows"},
{"School":"Northeastern University","State":"MA","Coach":"Ashley Pimentel"},
{"School":"Northern Arizona University","State":"AZ","Coach":"Julie Golden"},
{"School":"Northern Illinois University","State":"IL","Coach":"Joleen DeWitt"},
{"School":"Northern Kentucky University","State":"KY","Coach":"Lynlee Foster"},
{"School":"Northwestern University","State":"IL","Coach":"Sara Timmis"},
{"School":"Norwich University","State":"VT","Coach":"Rita Towne"},
{"School":"Nova Southeastern University","State":"FL","Coach":"Jackie George"},
{"School":"Oakland University","State":"MI","Coach":"Aimee Latsch"},
{"School":"Oberlin College","State":"OH","Coach":"Ric Weitzel"},
{"School":"Ohio State University","State":"OH","Coach":"Ollie Griffith"},
{"School":"Ohio University","State":"OH","Coach":"Karen Hiehle"},
{"School":"Ohio Wesleyan University","State":"OH","Coach":"Linda Dare"},
{"School":"Oklahoma Panhandle State University","State":"OK","Coach":"Malissa Meyer"},
{"School":"Old Dominion University","State":"VA","Coach":"Kasey Evans"},
{"School":"Oneonta State College","State":"NY","Coach":"Joycelyn Northup"},
{"School":"Oregon State University","State":"OR","Coach":"Dawn Ross"},
{"School":"Otterbein University","State":"OH","Coach":"Tenley Struhs"},
{"School":"Parkland College","State":"IL","Coach":"Megan Tyler"},
{"School":"Penn State Berks Equestrian Club","State":"PA","Coach":"Rebecca Weik"},
{"School":"Penn State Erie - The Behrend College","State":"PA","Coach":"Lew Trumble"},
{"School":"Penn State Harrisburg","State":"PA","Coach":"Alida Burkholder"},
{"School":"Penn State University","State":"PA","Coach":"Kerry Kocher"},
{"School":"Post University","State":"CT","Coach":"Justin Gregory"},
{"School":"Princeton University","State":"NJ","Coach":"Ashton Phillips"},
{"School":"Purdue University","State":"IN","Coach":"Gerald Steinmetz"},
{"School":"Purdue University Calumet","State":"IN","Coach":"Alexandra Moran"},
{"School":"Purdue University North Central","State":"IN","Coach":"Jennifer Turner"},
{"School":"Radford University","State":"VA","Coach":"Kimberly Huffman"},
{"School":"Randolph College","State":"VA","Coach":"Christopher Mitchell"},
{"School":"Randolph-Macon College","State":"VA","Coach":"John West"},
{"School":"Redlands Community College","State":"OK","Coach":"Dedra Baker"},
{"School":"Reedley College","State":"CA","Coach":"christina marin"},
{"School":"Rensselaer Polytechnic Institute","State":"NY","Coach":"Megan Rogers"},
{"School":"Rhode Island College","State":"RI","Coach":"Dana Stark"},
{"School":"Rice University","State":"TX","Coach":"Cathy Strobel"},
{"School":"Rider University","State":"NJ","Coach":"Andrea Hart-Sagolla"},
{"School":"Ripon College","State":"WI","Coach":"Mary Avery"},
{"School":"Roanoke College","State":"VA","Coach":"Carolyn Williams"},
{"School":"Rochester Institute of Technology","State":"NY","Coach":"Gail Miller"},
{"School":"Rocky Mountain College","State":"MT","Coach":"Chris Brown"},
{"School":"Roger Williams University","State":"RI","Coach":"Ted Torrey"},
{"School":"Rollins College","State":"FL","Coach":"Suzanne Muchow"},
{"School":"Rowan University","State":"NJ","Coach":"Ariel Frattaroli"},
{"School":"Rutgers University","State":"NJ","Coach":"Kelly Lamont-Francfort"},
{"School":"Sacred Heart University","State":"CT","Coach":"Tiffany Hajdasz"},
{"School":"Saginaw Valley State University","State":"MI","Coach":"Nancy Bellor"},
{"School":"Saint Leo University","State":"FL","Coach":"Grant Pennington"},
{"School":"Saint Louis University","State":"MO","Coach":"Jodi Gold"},
{"School":"Saint Mary's College","State":"IN","Coach":"Julie Harnish"},
{"School":"Saint Vincent College","State":"PA","Coach":"Veronica Ent"},
{"School":"Salem College","State":"NC","Coach":"Michelle Hargreaves"},
{"School":"Salisbury University","State":"MD","Coach":"Amy Walls"},
{"School":"Salve  Regina University","State":"RI","Coach":"Patrick March"},
{"School":"Santa Clara University","State":"CA","Coach":"Nicole Abercrombie"},
{"School":"Sarah Lawrence College","State":"NY","Coach":"Lori Rakoczy"},
{"School":"Savannah College of Art and Design","State":"GA","Coach":"Ashley Henry"},
{"School":"Seton Hill University","State":"PA","Coach":"Rebecca Bloom"},
{"School":"Shippensburg University","State":"PA","Coach":"Mary Bast"},
{"School":"Siena College","State":"NY","Coach":"Nora Hanlon"},
{"School":"Skidmore College","State":"NY","Coach":"Cindy Ford"},
{"School":"Slippery Rock University","State":"PA","Coach":"Amy Keefer"},
{"School":"Smith College","State":"MA","Coach":"Suzanne Payne"},
{"School":"Sonoma State University","State":"CA","Coach":"Michelle Davis"},
{"School":"Southeast Missouri State University","State":"MO","Coach":"SuAnne Remley"},
{"School":"Southern Illinois University Carbondale","State":"IL","Coach":"Jill O'Donoghue"},
{"School":"Southern Nazarene University","State":"OK","Coach":"Natalie Freeman"},
{"School":"Springfield College","State":"MA","Coach":"Dani Corkill"},
{"School":"St Cloud State University","State":"MN","Coach":"Samantha Cotter"},
{"School":"St. Andrews University","State":"NC","Coach":"Peggy McElveen"},
{"School":"St. Joseph's College","State":"NY","Coach":"sheila Rodgers"},
{"School":"St. Lawrence University","State":"NY","Coach":"Mary Drueding"},
{"School":"St. Mary-of-the-Woods College","State":"IN","Coach":"Sara Schulz"},
{"School":"St. Marys College of Maryland","State":"MD","Coach":"Leslie Allen"},
{"School":"Stanford University","State":"CA","Coach":"Vanessa Bartsch"},
{"School":"State University of New York at New Paltz","State":"NY","Coach":"Susan Clark"},
{"School":"State University of New York at Oswego","State":"NY","Coach":"Jillian Bergstresser"},
{"School":"Stetson University","State":"FL","Coach":"Beth Collier"},
{"School":"Stevens Institute of Technology","State":"NJ","Coach":"Patti Zwaan"},
{"School":"Stockton University","State":"NJ","Coach":"Stephanie Morrongiello"},
{"School":"Stonehill College","State":"MA","Coach":"kristen redquest"},
{"School":"Stony Brook University","State":"NY","Coach":"Myrna Treuting"},
{"School":"Suffolk County Community College","State":"NY","Coach":"deborah rittereiser"},
{"School":"SUNY Albany","State":"NY","Coach":"Tracy James-Pedersen"},
{"School":"SUNY Cobleskill","State":"NY","Coach":"Ray Whelihan"},
{"School":"SUNY Geneseo","State":"NY","Coach":"Kim Sanford"},
{"School":"Susquehanna University","State":"PA","Coach":"Jan Phillips"},
{"School":"Sweet Briar College","State":"VA","Coach":"Mimi Wroten"},
{"School":"Syracuse University","State":"NY","Coach":"Denise Van Patten"},
{"School":"Tarleton State University","State":"TX","Coach":"Annie Penrice"},
{"School":"Taylor University","State":"IN","Coach":"Margaret Boyle"},
{"School":"Temple University","State":"PA","Coach":"Jenn Post"},
{"School":"Tennessee Tech University","State":"TN","Coach":"Becky Huddleston"},
{"School":"Texas A&M; University-Commerce","State":"TX","Coach":"Brooke Harris"},
{"School":"Texas State University-San Marcos","State":"TX","Coach":"Katherine Deichmann"},
{"School":"Texas Tech University","State":"TX","Coach":"Lindsey Jones"},
{"School":"The University of Akron","State":"OH","Coach":"Laura Hearty"},
{"School":"The University of Oklahoma","State":"OK","Coach":"Laura Hoover"},
{"School":"The University of the South","State":"TN","Coach":"Allie Truitt"},
{"School":"Thiel College","State":"PA","Coach":"Jenna Malnar"},
{"School":"Tiffin Univeristy","State":"OH","Coach":"Julie Vogel"},
{"School":"Towson University","State":"MD","Coach":"Sandy Weinreich"},
{"School":"Transylvania University","State":"KY","Coach":"Tanya Davis"},
{"School":"Trinity College","State":"CT","Coach":"Amy Kriwitsky"},
{"School":"Trinity University","State":"TX","Coach":"Stephanie Cook"},
{"School":"Truman State University","State":"MO","Coach":"Emily Costello"},
{"School":"Tufts University","State":"MA","Coach":"Shane Powell"},
{"School":"Tulane University","State":"LA","Coach":"Kristen Swope"},
{"School":"U.S. Air Force Academy","State":"CO","Coach":"Allyson Hartenburg"},
{"School":"UNC-Chapel Hill","State":"NC","Coach":"Courtney Clayton"},
{"School":"Union College","State":"NY","Coach":"peggy aedjian"},
{"School":"United States Military Academy","State":"NY","Coach":"Peter and Sherry Cashman"},
{"School":"University at Buffalo","State":"NY","Coach":"Beth Walkowicz"},
{"School":"University of Alabama","State":"AL","Coach":"Ashley Morrison"},
{"School":"University of Arizona","State":"AZ","Coach":"Sheryl Gonnsen"},
{"School":"University of British Columbia","State":"BC","Coach":"Katrina Per"},
{"School":"University of California San Diego","State":"CA","Coach":"Mark Conley"},
{"School":"University of California, Berkeley","State":"CA","Coach":"Diane Yeager"},
{"School":"University of California, Davis","State":"CA","Coach":"Ryan Oropeza"},
{"School":"University of California, Los Angeles","State":"CA","Coach":"Carolin Malmkvist"},
{"School":"University of California, Santa Cruz","State":"CA","Coach":"Cassie Belmont"},
{"School":"University of California: Santa Barbara","State":"CA","Coach":"Alanna Snowden"},
{"School":"University of Central Florida","State":"FL","Coach":"Lesli Isaacson"},
{"School":"University of Cincinnati","State":"OH","Coach":"Missy Jo Hollingsworth"},
{"School":"University of Colorado - Colorado Springs","State":"CO","Coach":"Tracey Powers"},
{"School":"University of Colorado, Boulder","State":"CO","Coach":"Jill Pelzel"},
{"School":"University of Connecticut","State":"CT","Coach":"Alena Meacham"},
{"School":"University of Delaware","State":"DE","Coach":"Whitney Carmouche"},
{"School":"University of Findlay","State":"OH","Coach":"Cindy Morehead"},
{"School":"University of Florida","State":"FL","Coach":"Kim Burnette"},
{"School":"University of Georgia","State":"GA","Coach":"Katie Poteet"},
{"School":"University of Guelph","State":"ON","Coach":"Amy Noonan"},
{"School":"University Of Illinois at Urbana-Champaign","State":"IL","Coach":"Teresa (Terri) Foreman"},
{"School":"University of Kansas","State":"KS","Coach":"Elizabeth Gravatt"},
{"School":"University of Kentucky","State":"KY","Coach":"Diana Conlon"},
{"School":"University of Louisville","State":"KY","Coach":"Sarah Younger"},
{"School":"University of Maine","State":"ME","Coach":"Gail McCormack"},
{"School":"University of Mary Washington","State":"VA","Coach":"Teresa Seay"},
{"School":"University of Maryland","State":"MD","Coach":"Astrid Dalley"},
{"School":"University of Maryland, Baltimore County","State":"MD","Coach":"Sherri Trenary"},
{"School":"University of Massachusetts at Amherst","State":"MA","Coach":"Jillianne Smith"},
{"School":"University of Massachusetts Dartmouth","State":"MA","Coach":"Mary Charette"},
{"School":"University of Miami","State":"FL","Coach":"Karen Flynn"},
{"School":"University of Michigan","State":"MI","Coach":"Jennifer Blades"},
{"School":"University of Minnesota, Crookston","State":"MN","Coach":"Kayla Krueger"},
{"School":"University of Minnesota-Twin Cities","State":"MN","Coach":"Jamie Moeller"},
{"School":"University of Mississippi (Ole Miss)","State":"MS","Coach":"Gene (Beanie) Cone"},
{"School":"University of Montana","State":"MT","Coach":"Stephanie Kappes"},
{"School":"University of Montana Western","State":"MT","Coach":"Emelia Jones"},
{"School":"University of Nebraska-Lincoln","State":"NE","Coach":"Lori Jaixen"},
{"School":"University of New England","State":"ME","Coach":"Jackie Blackwell"},
{"School":"University of New Hampshire","State":"NH","Coach":"Christina Keim"},
{"School":"University of North Alabama","State":"AL","Coach":"Amy Smith"},
{"School":"University of North Carolina at Asheville","State":"NC","Coach":"Briana Ambrosic"},
{"School":"University of North Carolina at Charlotte","State":"NC","Coach":"Chelsea Dressler"},
{"School":"University of North Carolina Wilmington","State":"NC","Coach":"Lauryn Wiser"},
{"School":"University of North Carolina-Greensboro","State":"NC","Coach":"Allison Townley"},
{"School":"University of North Florida","State":"FL","Coach":"Julie Steinmetz-Usoff"},
{"School":"University of North Georgia","State":"GA","Coach":"Amanda Garner"},
{"School":"University of North Texas","State":"TX","Coach":"Courtney Burggren"},
{"School":"University of Notre Dame / Saint Mary's College","State":"IN","Coach":"Kerry Hilgendorf"},
{"School":"University of Oregon","State":"OR","Coach":"Courtney Horan"},
{"School":"University of Ottawa","State":"ON","Coach":"Mark Struthers"},
{"School":"University of Pennsylvania","State":"PA","Coach":"Dawne Morrone"},
{"School":"University of Pittsburgh","State":"PA","Coach":"James Boyce"},
{"School":"University of Rhode Island","State":"RI","Coach":"Wendy Brayman"},
{"School":"University of Richmond","State":"VA","Coach":"Jessica Boppe"},
{"School":"University of Rochester","State":"NY","Coach":"Peggy Gauger"},
{"School":"University of San Diego","State":"CA","Coach":"Alison Mundo"},
{"School":"University of Scranton","State":"PA","Coach":"Tara Lane Waitkus"},
{"School":"University of South Carolina","State":"SC","Coach":"Angela MacFawn"},
{"School":"University of South Carolina Aiken","State":"SC","Coach":"John Abbott"},
{"School":"University of South Florida","State":"FL","Coach":"Lauren Barth"},
{"School":"University of Southern California","State":"CA","Coach":"Kathryn Griffiths"},
{"School":"University of Tampa","State":"FL","Coach":"Sherri O'Connor"},
{"School":"University of Tennessee - Knoxville","State":"TN","Coach":"Lacey Johnston"},
{"School":"University of Texas at Austin","State":"TX","Coach":"Sydney Kornman"},
{"School":"University of Vermont","State":"VT","Coach":"Madeleine Austin"},
{"School":"University of Virginia","State":"VA","Coach":"Claiborne Bishop"},
{"School":"University of Washington","State":"WA","Coach":"Aidan Beaton"},
{"School":"University of West Florida","State":"FL","Coach":"Sierra Smallwood"},
{"School":"University of Western Ontario","State":"ON","Coach":"Hilary Rock"},
{"School":"University of Wisconsin - Eau Claire","State":"WI","Coach":"Tammy Olson"},
{"School":"University of Wisconsin-La Crosse","State":"WI","Coach":"Christy Lowell"},
{"School":"University of Wisconsin-Madison","State":"WI","Coach":"Mark Aplin"},
{"School":"University of Wisconsin-Milwaukee","State":"WI","Coach":"Lisa Behling"},
{"School":"University of Wisconsin-Platteville","State":"WI","Coach":"Mathea Durica"},
{"School":"University of Wisconsin-River Falls","State":"WI","Coach":"Peter RAYNE"},
{"School":"University of Wyoming","State":"WY","Coach":"Jessica Ford"},
{"School":"Utah State University","State":"UT","Coach":"Jason Romney"},
{"School":"Valley Forge Military College","State":"PA","Coach":"Sara McCoy Palmer"},
{"School":"Vanderbilt University","State":"TN","Coach":"Janelle Harcus"},
{"School":"Vassar College","State":"NY","Coach":"Michelle Clopp"},
{"School":"Villanova University","State":"PA","Coach":"Sara McCoy"},
{"School":"Virginia Commonwealth University","State":"VA","Coach":"Sulu Rose Reed"},
{"School":"Virginia Tech","State":"VA","Coach":"Sherri West"},
{"School":"Wake Forest University","State":"NC","Coach":"Michelle Hargreaves"},
{"School":"Washington & Jefferson College","State":"PA","Coach":"Olivia DeCesar"},
{"School":"Washington and Lee University","State":"VA","Coach":"Gordon Reistrup"},
{"School":"Washington College","State":"MD","Coach":"Chris Bigelow"},
{"School":"Washington State University","State":"WA","Coach":"Katharina Whetzel"},
{"School":"Washington University in St. Louis","State":"MO","Coach":"Patti Boland"},
{"School":"Wellesley College","State":"MA","Coach":"Alli Mitchell"},
{"School":"Wesleyan College","State":"GA","Coach":"Jessica Denniston"},
{"School":"Wesleyan University","State":"CT","Coach":"Armand Chenelle"},
{"School":"West Chester University","State":"PA","Coach":"Wendy Myers"},
{"School":"West Texas A&M; University","State":"TX","Coach":"Amanda Love"},
{"School":"West Virginia University","State":"WV","Coach":"Bobby Dean"},
{"School":"Western Carolina University","State":"NC","Coach":"Angela Fowler"},
{"School":"Western Illinois University","State":"IL","Coach":"kayla weikert"},
{"School":"Western Kentucky University","State":"KY","Coach":"CHARLES ANDERSON"},
{"School":"Western Michigan University","State":"MI","Coach":"Rob Stewart"},
{"School":"Western Washington University","State":"WA","Coach":"Ashley Greyell"},
{"School":"Westfield State University","State":"MA","Coach":"Frances Cross"},
{"School":"Westminster College","State":"PA","Coach":"Janet Rowan"},
{"School":"Wheaton College","State":"MA","Coach":"Carly Fisher"},
{"School":"Whittier College","State":"CA","Coach":"Patty Foltz Mccarty"},
{"School":"William Paterson University","State":"NJ","Coach":"Hayley Rooney"},
{"School":"Williams College","State":"MA","Coach":"Lisa DeMayo"},
{"School":"Wilmington College","State":"OH","Coach":"Jennifer Riddle"},
{"School":"Wilson College","State":"PA","Coach":"Megan Mendenhall"},
{"School":"Wofford College","State":"SC","Coach":"Jeanne Smith"},
{"School":"Worcester State University","State":"MA","Coach":"Tamara Johnston"},
{"School":"Xavier University","State":"OH","Coach":"Maria Kneipp"},
{"School":"Yale University","State":"CT","Coach":"Jennifer Thompson"},
{"School":"Youngstown State University","State":"OH","Coach":"Amy Watkins"}]


while True:
    print('Enter a state abbreviation: (blank to quit)')
    state = input()
    if state == '':
        break

    if state in schools_list:
        print
        (schools_list[state] + ' is the birthday of ' + state)
    else:
        print('I do not have birthday information for ' + state)
        print
        ('What is their birthday?')
        bday = input()
        schools_list[state] = bday
        print
        ('Birthday database updated.')
